name: Merge Docs to gh-pages
on: 
  push:
    branches:
    - 'develop' # Can I get it to push to develop only when the PR has a change in the `doc` directory?
    - 'feature/automate-ghp'
    - 'feature/test-gh-actions'
  workflow_dispatch:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache-doxygen
        uses: actions/cache@v4
        with:
          path: |
            ~/.doxygen
            ~/usr/local/bin/doxygen
          key: ${{ runner.os }}-doxygen-${{ hashFiles( '**/install_doxygen.sh' ) }}
      - name: Install Doxygen
        if: steps.cache-doxygen.outputs.cache-hit != 'true'
        run: .github/scripts/install_doxygen.sh
      - name: Update code
        env: 
          - FIND: option(ENABLE_DOCS "Enable generation of doxygen-based documentation." OFF)
          - REPLACE: option(ENABLE_DOCS "Enable generation of doxygen-based documentation." ON)
        run: | 
#"sed -i 's/option(ENABLE_DOCS "Enable generation of doxygen-based documentation." OFF)/option(ENABLE_DOCS "Enable generation of doxygen-based documentation." ON)/g' CMakeLists.txt"
          sed -i 's/$FIND/$REPLACE/g' CMakeLists.txt
          sed -i 's/make install/make doc/g' tests/compile_upp.sh
# "sed -i'.bak' -e 's/make install/make doc/g' tests/compile_upp.sh"
      - name: Build docs
        run: cd tests && ./compile_upp.sh
      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with: 
          path: tests/build/html
  #update-docs:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  # Find out about permissions! 
  #  permissions: 
  #    pages: write
  #    id-token: write 
    #Find out about environment & outputs! 
  #  environment: 
  #    name: github-pages
  #    url: ${{ steps.deployment.output.page_url }}
  #  steps: 
  #    - name: Deploy HTMLs
  #      id: deployment
  #      uses: actions/deploy-pages@v4
        

          


